INSERT INTO Products(Name, Category_Id) VALUES('Milk 1l', 4);
INSERT INTO Products(Name, Category_Id) VALUES('Imasi', 4);
INSERT INTO Products(Name, Category_Id) VALUES('Bread', 2);
INSERT INTO Products(Name, Category_Id) VALUES('Chakalaka Can',1);
INSERT INTO Products(Name, Category_Id) VALUES('Gold Dish Vegetable Curry Can',1);
INSERT INTO Products(Name, Category_Id) VALUES('Fanta 500ml',5);
INSERT INTO Products(Name, Category_Id) VALUES('Coke 500ml',5);
INSERT INTO Products(Name, Category_Id) VALUES('Cream Soda 500ml',5);
INSERT INTO Products(Name, Category_Id) VALUES('Iwisa Pap 5kg',2);
INSERT INTO Products(Name, Category_Id) VALUES('Top Class Soy Mice',1);
INSERT INTO Products(Name, Category_Id) VALUES('Shampoo 1 litre',3);
INSERT INTO Products(Name, Category_Id) VALUES('Soap Bar',3);
INSERT INTO Products(Name, Category_Id) VALUES('Bananas - loose',6);
INSERT INTO Products(Name, Category_Id) VALUES('Apples - loose',6);
INSERT INTO Products(Name, Category_Id) VALUES('Mixed Sweets 5s',8);
INSERT INTO Products(Name, Category_Id) VALUES('Heart Chocolates',8);
INSERT INTO Products(Name, Category_Id) VALUES('Rose (plastic)',7);
INSERT INTO Products(Name, Category_Id) VALUES('Valentine Cards',7);
